sudo: required
services:
    - docker

before_install:
    - docker build -t codixir/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true codixir/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-066120337496"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY